version: '3.8'

services:
  autocast-api:
    build: .
    ports:
      - '8000:8000'
    environment:
      # You can override these in a .env file
      - OMDB_API_KEY=${OMDB_API_KEY}
    volumes:
      # Mount the .env file if it exists
      - ./.env:/app/.env:ro
      # Mount config.yaml if you want to modify it without rebuilding
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
